### ISSUE TITLE
Cannot find module '@netlify/functions'

### ISSUE THREAD

**Issue by lukasborawski** [netlify/functions#340]
Hello. So I'm using scheduled functions and along with the dev env/mode it's working fine, I can serve it and invoke it. But as long I'm putting this to the server I have this error:

```bash
ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module '@netlify/functions' ... 
```

The package is defined as a dependency in the `package.json`, and this is my function:

```js
const { schedule } = require('@netlify/functions')

exports.handler = schedule('@hourly', async (event) => {
  const eventBody = JSON.parse(event.body)
  console.log(`Next function run at ${eventBody.next_run}.`)
  // function init
  return {
    statusCode: 200,
  }
})
```

Netlify config:

```toml
[build]
    functions = "functions"
     publish = "./"

[functions]
    directory = "functions/"
    external_node_modules = ["canvas", "jsdom"]

```

Functions are enabled on the Labs and Project page. What is wrong? Thanks for the help in advance.
